name: WoT
markdown: kramdown

navigation:
 - title: W3C
   url: /wot-pages/w3c/
 - title: News & Events
   url: /wot-pages/news-and-events/
 - title: Developer
   url: /wot-pages/developer/
 - title: Liasons & Testimonals
   url: /wot-pages/liasons/
 - title: Specifications
   url: /wot-pages/specifications/
 - title: Contact
   url: /wot-pages/contact/
