name: WoT
markdown: kramdown

# uncomment if in root
baseurl: "/wot-pages"

navigation:
# - title: W3C
#   url: /wot-pages/w3c/
 - title: Working Group
   url: /wot-pages/wg/
 - title: Interest Group
   url: /wot-pages/ig/
 - title: Community Group
   url: /wot-pages/cg/
# - title: News & Events
#   url: /wot-pages/news-and-events/
# - title: Getting Started
#   url: /wot-pages/getting-started/
 - title: Developers
   url: /wot-pages/developers/
# - title: Members
#   url: /wot-pages/members/
# - title: Liasons & Testimonals
#   url: /wot-pages/liasons/
# - title: Specifications
#   url: /wot-pages/specifications/
# - title: Contact
#   url: /wot-pages/contact/
